### ISSUE TITLE
Code không chạy

### ISSUE THREAD

**Issue by quangtrongonline** [doanguyen/lasotuvi#6]
Xin chào, mình đang cài và chạy thử source này trên localhost thì bị báo lỗi không lấy được lá số. Xem trong console thì thấy lỗi này  http://lasotuvi.local/frontend/api.... ( 404 (Not Found) ).
Còn khi chạy 

> python manage.py runserver

**thì báo lỗi** 
```
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000236431FA7B8>
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "E:\Python\lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "E:\Python\lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "E:\Python\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "E:\Python\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "E:\Python\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "E:\Python\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "E:\Python\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Python\lib\site-packages\django\urls\resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "E:\Python\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Python\lib\site-packages\django\urls\resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "E:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Ampps\www\lasotuvi\lasotuvi\urls.py", line 8, in <module>
    from src.DiaBan import diaBan
ModuleNotFoundError: No module named 'src'
```
Bạn xem giúp mình với. 
Cám ơn bạn nhiều

**Comment by doanguyen** [comment]
Chào bạn, cám ơn bạn đã quan tâm đến project.

Hiện tại lasotuvi chạy trên phiên bản django đã cũ nên không còn compatible, mình đang trong quá trình hoàn thiện phiên bản 2, hy vọng cuối tuần này sẽ xong.

**Comment by quangtrongonline** [comment]
(like) rất vui khi bạn vẫn phát triển projetc này. Wating for new version....
Tks again!

**Comment by doanguyen** [comment]
Mình đã update rồi nhé.

:D
